volumes:
  mysql:

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: brasileirao_dump
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    ports:
      - 6379:6379